version: '3'
services:

  nginx:
    image: nginx:1.15-alpine
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - web

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - default
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL: ${EMAIL}
      PASSE: ${PASSE}
      PROD_SERVER: ${PROD_SERVER}

  web:
    build:
      context: .
      dockerfile: client/Dockerfile
    networks:
      - default

networks:
  default:
