version: '3'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d

  api:
    image: node:latest

  web:
    image: node:latest
