export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILED = 'ADMIN_LOGIN_FAILED';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const GET_ALL_CLIENTS_REQUEST = 'GET_ALL_CLIENTS_REQUEST';
export const GET_ALL_CLIENTS_SUCCESS = 'GET_ALL_CLIENTS_SUCCESS';
export const GET_ALL_CLIENTS_FAILED = 'GET_ALL_CLIENTS_FAILED';

export const GET_SINGLE_CLIENT_REQUEST = 'GET_SINGLE_CLIENT_REQUEST';
export const GET_SINGLE_CLIENT_SUCCESS = 'GET_SINGLE_CLIENT_SUCCESS';
export const GET_SINGLE_CLIENT_FAILED = 'GET_SINGLE_CLIENT_FAILED';
export const HOTSPOT_DELETE = 'HOTSPOT_DELETE';

export const ADD_NEW_CLIENT_REQUEST = 'ADD_NEW_CLIENT_REQUEST';
export const ADD_NEW_CLIENT_SUCCESS = 'ADD_NEW_CLIENT_SUCCESS';
export const ADD_NEW_CLIENT_FAILED = 'ADD_NEW_CLIENT_FAILED';
export const ADD_NEW_CLIENT_RESET = 'ADD_NEW_CLIENT_RESET';

export const DELETE_SINGLE_CLIENT_REQUEST = 'DELETE_SINGLE_CLIENT_REQUEST';
export const DELETE_SINGLE_CLIENT_SUCCESS = 'DELETE_SINGLE_CLIENT_SUCCESS';
export const DELETE_SINGLE_CLIENT_FAILED = 'DELETE_SINGLE_CLIENT_FAILED';
export const DELETE_SINGLE_CLIENT_RESET = 'DELETE_SINGLE_CLIENT_RESET';

export const ADD_HOTSPOT_TO_CLIENT_REQUEST = 'ADD_HOTSPOT_TO_CLIENT_REQUEST';
export const ADD_HOTSPOT_TO_CLIENT_SUCCESS = 'ADD_HOTSPOT_TO_CLIENT_SUCCESS';
export const ADD_HOTSPOT_TO_CLIENT_FAILED = 'ADD_HOTSPOT_TO_CLIENT_FAILED';
export const ADD_HOTSPOT_TO_CLIENT_RESET = 'ADD_HOTSPOT_TO_CLIENT_RESET';

export const HOTSPOT_UPDATE_REQUEST = 'HOTSPOT_UPDATE_REQUEST';
export const HOTSPOT_UPDATE_SUCCESS = 'HOTSPOT_UPDATE_SUCCESS';
export const HOTSPOT_UPDATE_FAILED = 'HOTSPOT_UPDATE_FAILED';
export const HOTSPOT_UPDATE_RESET = 'HOTSPOT_UPDATE_RESET';

export const CLIENT_UPDATE_REQUEST = 'CLIENT_UPDATE_REQUEST';
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS';
export const CLIENT_UPDATE_FAILED = 'CLIENT_UPDATE_FAILED';
export const CLIENT_UPDATE_RESET = 'CLIENT_UPDATE_RESET';

export const CLIENT_LOGIN_REQUEST = 'CLIENT_LOGIN_REQUEST';
export const CLIENT_LOGIN_SUCCESS = 'CLIENT_LOGIN_SUCCESS';
export const CLIENT_LOGIN_FAILED = 'CLIENT_LOGIN_FAILED';
export const CLIENT_LOGOUT = 'CLIENT_LOGOUT';
